export const GET_ALL_COURSES = "GET_ALL_COURSES";
export const GET_TOTAL_COURSES = "GET_TOTAL_COURSES";
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID";
export const UPDATE_COURSE_STATUS = "UPDATE_COURSE_STATUS";